farmacia/config/routes.rb
Rails.application.routes.draw do
  resources :sales, only: [:index, :show, :new, :edit, :create, :update]
  resources :categories
  resources :medicaments, only: [:index, :show, :new, :edit, :create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home
  root 'home#index'

  resources :sessions, only: [:create, :new, :destroy]
  get '/signup', to: 'users#index'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  namespace :api do
    resources :medicaments, only: [:index, :show, :create, :update]
  end

  namespace :api do
    resources :categories
  end

  # constraints subdomain: 'api' do
  #   scope module: 'api' do
  #     resources :medicaments
  #   end
  # end
end

farmacia/app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="navbar-brand">Farmácia</div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <%= link_to 'Home', root_path, class:"nav-link" %>
                </div>
                <% if current_user_admin? %>
                    <div class="navbar-nav">
                        <%= link_to 'Categorias', categories_path, class:"nav-link" %>
                    </div>
                    <div class="navbar-nav">
                        <%= link_to 'Medicamentos', medicaments_path, class:"nav-link" %>
                    </div>
                <% end %>
                <div class="navbar-nav">
                    <% if current_user_admin? %>
                        <%= link_to 'Vendas', sales_path, class:"nav-link" %>
                    <% else %>
                        <%= link_to 'Compras', sales_path, class:"nav-link" %>
                    <% end %>
                </div>
                <% if logged_in? %>
                    <div class="navbar-nav">
                        <%= link_to "Sair", logout_path, class: "nav-link",  method: :delete %>
                    </div>
                <% else %>
                    <div class="navbar-nav">
                        <%= link_to "Entrar", signup_path, class: "nav-link" %>
                    </div>
                <% end %>
            </div>
        </div>
    </nav>
</header>

farmacia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Farmácia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
  </head>

  <body>
    <%= render "layouts/header" %>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>