farmacia/config/routes.rb
Rails.application.routes.draw do
  resources :sales, only: [:index, :show, :new, :edit, :create, :update]
  resources :categories
  resources :medicaments, only: [:index, :show, :new, :edit, :create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home
  root 'home#index'

  resources :sessions, only: [:create, :new, :destroy]
  get '/signup', to: 'users#index'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  namespace :api do
    resources :medicaments, only: [:index, :show, :create, :update]
  end

  namespace :api do
    resources :categories
  end

  # constraints subdomain: 'api' do
  #   scope module: 'api' do
  #     resources :medicaments
  #   end
  # end
end

farmacia/app/models/medicament.rb
class Medicament < ApplicationRecord
    belongs_to :category
    has_many :saleDetails
    has_many :sales, through: :saleDetails
    validates :name, :description, :price, presence: true
    paginates_per 10
end

farmacia/app/controllers/api/medicaments_controller.rb
class Api::MedicamentsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_medicament, only: %i[ show edit update destroy ]

    # GET /medicaments or /medicaments.json
    def index
        @medicaments = Medicament.all

        render json: @medicaments
    end

    # GET /medicaments/1 or /medicaments/1.json
    def show
        render json: @medicament
    end

    # POST /medicaments or /medicaments.json
    def create
        @medicament = Medicament.new(medicament_params)

        if @medicament.save
            render json: @medicament
        else
            render json: @medicament.errors, status: :unprocessable_entity
        end
    end

    # PATCH/PUT /medicaments/1 or /medicaments/1.json
    def update
        if @medicament.update(medicament_params)
            render json: @medicament
        else
            render json: @medicament.errors, status: :unprocessable_entity
        end
    end

    # DELETE /medicaments/1 or /medicaments/1.json
    def destroy
        @medicament.destroy
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_medicament
            @medicament = Medicament.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def medicament_params
            params.require(:medicament).permit(:name, :description, :price, :category_id)
        end
end

farmacia/app/controllers/medicaments_controller.rb
class MedicamentsController < ApplicationController
  before_action :set_medicament, only: %i[ show edit update destroy ]

  # GET /medicaments or /medicaments.json
  def index
    @medicaments = Medicament.order('id DESC').page params[:page]
  end

  # GET /medicaments/1 or /medicaments/1.json
  def show
  end

  # GET /medicaments/new
  def new
    @medicament = Medicament.new
    @categories = Category.all
  end

  # GET /medicaments/1/edit
  def edit
    @categories = Category.all
  end

  # POST /medicaments or /medicaments.json
  def create
    @medicament = Medicament.new(medicament_params)

    respond_to do |format|
      if @medicament.save
        format.html { redirect_to @medicament, notice: "Medicamento cadastrado com sucesso." }
        format.json { render :show, status: :created, location: @medicament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medicament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicaments/1 or /medicaments/1.json
  def update
    respond_to do |format|
      if @medicament.update(medicament_params)
        format.html { redirect_to @medicament, notice: "Medicamento atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @medicament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medicament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicaments/1 or /medicaments/1.json
  def destroy
    @medicament.destroy
    respond_to do |format|
      format.html { redirect_to medicaments_url, notice: "Medicamento removido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicament
      @medicament = Medicament.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medicament_params
      params.require(:medicament).permit(:name, :description, :price, :category_id)
    end
end

farmacia/app/helpers/api/medicaments_helper.rb
module Api::MedicamentsHelper
end

farmacia/app/helpers/medicaments_helper.rb
module MedicamentsHelper
end

farmacia/app/views/medicaments/_form.html.erb
<%= form_with(model: medicament, local: true) do |form| %>
  <% if medicament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicament.errors.count, "error") %> prohibited this medicament from being saved:</h2>

      <ul>
      <% medicament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :description, 'Descrição' %>
    <%= form.text_area :description, :cols => 20, :rows => 8, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :price, 'Preço' %>
    <%= form.number_field :price, step: :any, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :category_id, 'Categoria' %>
    <%= collection_select(:medicament, :category_id, @categories, :id, :name) %>
  </div>

  <div class="actions form-group mt-3">
    <%= link_to 'Cancelar', medicaments_path, class: 'btn btn-secondary' %>
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
  </div>
<% end %>

farmacia/app/views/medicaments/edit.html.erb
<h1 class="mt-5">Editar Medicamento</h1>

<%= render 'form', medicament: @medicament %>

farmacia/app/views/medicaments/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible fade show mt-3" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<h1 class="mt-5">Medicamentos</h1>

<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Preço</th>
      <th>Categoria</th>
      <th style="width: 140px;" class="text-center">Operações</th>
    </tr>
  </thead>

  <tbody>
    <% @medicaments.each do |medicament| %>
      <tr>
        <td><%= medicament.name %></td>
        <td><%= medicament.description %></td>
        <td><%= number_to_currency(medicament.price, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
        <td><%= medicament.category ? medicament.category.name : medicament.category %></td>
        <td>
          <%= link_to medicament, class: "btn btn-outline-dark btn-sm" do %>
            <i class="fas fa-search"></i>
          <% end %>
          <%= link_to edit_medicament_path(medicament), class: "btn btn-outline-dark btn-sm" do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @medicaments %>
<br>

<%= link_to 'Novo Medicamento', new_medicament_path, class: 'btn btn-primary' %>

farmacia/app/views/medicaments/new.html.erb
<h1 class="mt-5">Novo Medicamento</h1>

<%= render 'form', medicament: @medicament %>

farmacia/app/views/medicaments/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible fade show mt-3" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<h1 class="mt-5">Medicamento</h1>

<p class="mt-3">
  <strong>Nome:</strong>
  <%= @medicament.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @medicament.description %>
</p>

<p>
  <strong>Preço:</strong>
  <%= number_to_currency(@medicament.price, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
</p>

<div class="mt-5">
  <%= link_to 'Voltar', medicaments_path, class: 'btn btn-primary' %>
  <%= link_to 'Editar', edit_medicament_path(@medicament), class: 'btn btn-primary' %>
</div>