farmacia/config/routes.rb
Rails.application.routes.draw do
  resources :sales, only: [:index, :show, :new, :edit, :create, :update]
  resources :categories
  resources :medicaments, only: [:index, :show, :new, :edit, :create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home
  root 'home#index'

  resources :sessions, only: [:create, :new, :destroy]
  get '/signup', to: 'users#index'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  namespace :api do
    resources :medicaments, only: [:index, :show, :create, :update]
  end

  namespace :api do
    resources :categories
  end

  # constraints subdomain: 'api' do
  #   scope module: 'api' do
  #     resources :medicaments
  #   end
  # end
end

farmacia/app/models/sale.rb
class Sale < ApplicationRecord
    has_many :saleDetails
    has_many :medicaments, through: :saleDetails
    validates :date_sale, :user_id, :user, presence: true
    paginates_per 10
end

farmacia/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    if session[:user_authority] == "ADMIN"
      @sales = Sale.order('id DESC').page params[:page]
    else
      @sales = Sale.where("user_id = #{session[:user_id]}").order('id DESC').page params[:page]
    end
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @medicaments = Medicament.all
  end

  # GET /sales/1/edit
  def edit
    @medicaments = Medicament.all
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new

    @sale.user_id = session[:user_id]
    @sale.user = session[:user_name]
    @sale.date_sale = DateTime.current.to_date

    price = 0

    sale_params[:medicaments].each do |medicament|
      medicament = Medicament.find(medicament)
      price += medicament.price
    end

    sale_params[:medicaments].each do |medicament|
      @sale.saleDetails.build(:price => price, :medicament_id => medicament)
    end

    respond_to do |format|
      if @sale.save
        p @sale
        format.html { redirect_to @sale, notice: "Compra realizada com sucesso." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "Compra atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Compra removida com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:medicaments => [])
    end
end

farmacia/app/helpers/sales_helper.rb
module SalesHelper
end

farmacia/app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p class="mt-3">
    <strong>Data da compra:</strong>
    <%= format_date(DateTime.current.to_date) %>
  </p>

  <div class="field form-group">
    <%= form.label :medicaments, 'Medicamentos' %>
    <%= form.collection_select(:medicaments, @medicaments, :id, :name, {:include_hidden => false, :selected => @medicaments.first.id}, {:multiple => true}) %>
  </div>

  <div class="actions form-group mt-3">
    <%= link_to 'Cancelar', sales_path, class: 'btn btn-secondary' %>
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
  </div>
<% end %>

farmacia/app/views/sales/edit.html.erb
<h1 class="mt-5">Editar Compra</h1>

<%= render 'form', sale: @sale %>

farmacia/app/views/sales/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible fade show mt-3" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if !current_user_admin? %>
  <h1 class="mt-5">Compras</h1>
<% else %>
  <h1 class="mt-5">Vendas</h1>
<% end %>

<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Data</th>
      <% if current_user_admin? %>
        <th>Cliente</th>
      <% end %>
      <th>Qtd. Itens</th>
      <th>Total</th>
      <th style="width: 140px;">Operações</th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= format_date(sale.date_sale) %></td>
        <% if current_user_admin? %>
          <td><%= sale.user %></td>
        <% end %>
        <td><%= sale.saleDetails.length() %></td>
        <td><%= number_to_currency(sale.saleDetails[0].price, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
        <td>
          <%= link_to sale, class: "btn btn-outline-dark btn-sm" do %>
            <i class="fas fa-search"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @sales %>
<br>

<% if !current_user_admin? %>
  <%= link_to 'Nova Compra', new_sale_path, class: 'btn btn-primary' %>
<% end %>

farmacia/app/views/sales/new.html.erb
<h1 class="mt-5">Nova Compra</h1>

<%= render 'form', sale: @sale %>

farmacia/app/views/sales/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible fade show mt-3" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if !current_user_admin? %>
  <h1 class="mt-5">Compra</h1>
<% else %>
  <h1 class="mt-5">Venda</h1>
<% end %>

<p class="mt-3">
  <strong>Data da compra:</strong>
  <%= format_date(@sale.date_sale) %>
</p>

<div>
  <strong>Medicamentos:</strong>
  <ul>
    <% @sale.saleDetails.each do |sale| %>
      <li>
        <%= sale.medicament.name %> - <%= number_to_currency(sale.medicament.price) %>
      </li>
    <% end %>
  </ul>
</div>

<p class="mt-3">
  <strong>Total:</strong>
  <%= number_to_currency(@sale.saleDetails[0].price, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
</p>

<div class="mt-5">
  <%= link_to 'Voltar', sales_path, class: 'btn btn-primary' %>
</div>